project:
  type: website

website: 
  title: "Practice in Data Analysis"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: syllabus.qmd
        text: Syllabus

      - href: resources.qmd
        text: Resources

      - href: about.qmd
        text: About      


  sidebar:
    style: docked
    search: true

    contents:
      - section: "Lecture Notes"
        contents:
          - week01.qmd
          - week02.qmd
          

format:
  html:
    theme: litera
    toc: true 