---
title: 
date: 
output: 
  pdf_document:
    latex_engine: xelatex
mainfont: NanumGothic
papersize: a4
header-includes:
#     - \usepackage{setspace}\onehalfspacing
    - \usepackage{setspace}\doublespacing
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(janitor)
library(skimr)
library(patchwork)
library(gapminder)
df2007 <- gapminder |> 
  filter(year == 2007)
```


## 수치형 변수 1개: 히스토그램과 상자그림


```{r}
p1 <- df2007 |> ggplot(aes(x =lifeExp)) + geom_histogram()
p2 <- df2007 |> ggplot(aes(x =lifeExp)) + geom_boxplot()
p1 + p2
```


## 수치형 변수 2개의 관계: 산점도


```{r}
p3 <-  df2007 |> ggplot(aes(x = gdpPercap, y = lifeExp)) +
  geom_point()

p4 <- df2007 |> ggplot(aes(x = gdpPercap, y = lifeExp)) +
  geom_point() +
  scale_x_log10()
p3 + p4
```
\newpage

```{r}
df2007 <- df2007 |>
  mutate(income_group = cut(gdpPercap, 
                            breaks = quantile(gdpPercap, probs = c(0, 1/3, 2/3, 1)),
                            labels = c("Low", "Medium", "High"),
                            include.lowest = TRUE
                        )
  )
```

## 범주형 변수 1개: 도수분포표와 막대그래프

```{r}
df2007 |> tabyl(continent) |> 
  adorn_pct_formatting()
```

\vspace{2cm}

```{r}
df2007 |> ggplot(aes(x = continent)) +
  geom_bar()
```

\newpage


## 범주형 변수 2개의 관계: 교차표와 중첩막대그래프

```{r}
df2007 |> tabyl(continent, income_group) |>
  adorn_totals("col") |> 
  adorn_percentages("row") |> 
  adorn_pct_formatting() |> 
  adorn_ns()
```

\vspace{2cm}


```{r}
p5 <- df2007 |> ggplot(aes(x = continent, fill = income_group)) +
  geom_bar()

p6 <- df2007 |> ggplot(aes(x = continent, fill = income_group)) +
  geom_bar(position = "dodge")

p7 <- df2007 |> ggplot(aes(x = continent, fill = income_group)) +
  geom_bar(position = "fill")   
(p5 + p6) / (p7 + plot_spacer())
```

\newpage


## 범주별로 수치형 변수의 분포 전체를 제시: 분할차트, 병렬상자그림


```{r, fig.align = 'center'}
p8 <- ggplot(df2007, aes(y = lifeExp)) +
  geom_boxplot() +
  facet_wrap(~continent)    
p9 <- ggplot(df2007, aes(x = continent, y = lifeExp)) +
  geom_boxplot()    
p8 + p9
```



## 범주별로 두 수치형 변수의 관계를 제시



```{r, fig.align = 'center', out.width = "80%",}
df2007 |> ggplot(aes(x = gdpPercap, y = lifeExp, color = continent)) +
  geom_point()
```

\newpage

## 범주별로 수치형 변수의 통계량을 제시

```{r}
gapminder |> group_by(continent) |>
  summarize(mean_lifeExp = mean(lifeExp))     
```

\vspace{2cm}

```{r}
gapminder |> group_by(continent) |>
  summarize(mean_lifeExp = mean(lifeExp)) |>
  ggplot(aes(x = continent, y = mean_lifeExp)) +
     geom_col()  
```

\newpage

## 시간에 따른 변화를 나타내는 차트: 선그래프

```{r}
gapminder |> group_by(year, continent) |>
  summarize(mean_lifeExp = mean(lifeExp)) |>
  ggplot(aes(x = year, y = mean_lifeExp, color = continent)) +
     geom_line()     
```
